const LOCAL_MODEL_CATEG_FALLBACK = '0'
const LOCAL_MODEL_PROBA_FALLBACK = 0.1
const LOCAL_MODEL_PCT_TOKENS_IN_VOC_THRESHOLD = 0.1

module.exports = {
  LOCAL_MODEL_CATEG_FALLBACK,
  LOCAL_MODEL_PROBA_FALLBACK,
  LOCAL_MODEL_PCT_TOKENS_IN_VOC_THRESHOLD
}
